psytests/administration/urls.py
from django.urls import path

from .views import (
    AssignedUsers,
    Home,
    PendingUsers,
    SetSchedule,
    UserDetailView,
    RQuestionsTemplateView,
    PQuestionsTemplateView,
    RQuestionsCreateView,
    PQuestionsCreateView,
    RQuestionsEditView,
    PQuestionsEditView,
    RDeleteQuestions,
    PDeleteQuestions,
    HistorySchedules,
    MissedSchedules,
    ResetSchedule,
    UpcomingSchedules,
    UserDetailUpdate,
    UserManagement,
    UserSchedules,
    approve_user,
    deleteRecord,
    return_user,
    send_msg,
)


app_name='administration'

urlpatterns=[
    path('', Home.as_view(), name='home'),
    path('user-management/', UserManagement.as_view(), name='user-management'),
    path('user-management/<int:pk>/update', UserDetailUpdate.as_view(), name='user-detail-update'),
    path('pending-users/', PendingUsers.as_view(), name='pending-users'),
    path('assigned-users/', AssignedUsers.as_view(), name='assigned-users'),
    path('user-results/<user>/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user-results/<user>/<int:pk>/approve', approve_user, name='approve-user'),
    path('user-results/<user>/<int:pk>/return', return_user, name='return-user'),
    path('user-results/delete/<int:r_pk>/<r_user>/<int:p_pk>/<p_user>/', deleteRecord, name='delete-record'),
    path('user-results/<username>/set-schedule/', SetSchedule.as_view(), name='set-schedule'),
    path('schedules/', UserSchedules.as_view(), name='schedules'),
    path('schedules/missed/', MissedSchedules.as_view(), name='missed-schedules'),
    path('schedules/upcoming/', UpcomingSchedules.as_view(), name='upcoming-schedules'),
    path('schedules/history/', HistorySchedules.as_view(), name='history-schedules'),
    path('schedules/<int:pk>/reset-schedule/', ResetSchedule.as_view(), name='reset-schedule'),
    path('rquestions/', RQuestionsTemplateView.as_view(), name='rquestions'),
    path('pquestions/', PQuestionsTemplateView.as_view(), name='pquestions'),
    path('rquestions/create/riasec/', RQuestionsCreateView.as_view(), name='rquestions_add'),
    path('pquestions/create/personality/', PQuestionsCreateView.as_view(), name='pquestions_add'),
    path('rquestions/<slug:slug>/riasec/edit', RQuestionsEditView.as_view(), name='rquestions_edit'),
    path('pquestions/<slug:slug>/personality/edit', PQuestionsEditView.as_view(), name='pquestions_edit'),
    path('rquestions/<slug:slug>/riasec/delete', RDeleteQuestions.as_view(), name='rquestions_delete'),
    path('pquestions/<slug:slug>/personality/delete', PDeleteQuestions.as_view(), name='pquestions_delete'),
    path('<user>/send-msg', send_msg, name='send-msg'),
]

psytests/psytests/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from accounts.forms import CustomizedPasswordResetForm, CustomizedPasswordResetConfirmForm
from psytests.views import Assessment, DataPrivacyConsent, HomePageView, Awesome

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
        path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset_form.html', email_template_name='accounts/password_reset_email.html', form_class=CustomizedPasswordResetForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', form_class=CustomizedPasswordResetConfirmForm), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('', HomePageView.as_view(), name="homepage"),
    path('assessment/', Assessment.as_view(), name="assessment"),
    path('awesome/', Awesome.as_view(), name="awesome"),
    path('<str:test>/data/privacy/consent', DataPrivacyConsent.as_view(), name="consent"),
    path('auth/', include('accounts.urls')), #Connects to psytest folder urls.py
    path('career/',include('riasec.urls')), #Connects to riasec folder urls.py
    path('personality/',include('personalityTest.urls')), #Connects to personalityTest folder urls.py
    path('accounts/', include('allauth.urls')),
    path('administration/', include('administration.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psytests/riasec/urls.py
from django.urls import path
from .views import Home, ResultPage
from . import views

app_name='riasec'
urlpatterns = [
    path('test/', views.testPage, name='test'),
    path('home/', Home.as_view(), name='home'),
    path('result/', ResultPage.as_view(), name='result'),
    path('test/evaluate/', views.evaluate, name='test_evaluate'),
]

psytests/administration/forms.py
from django import forms
from accounts.models import Profile

from personalityTest.models import Questionnaire
from riasec.models import RIASEC_Test

from personalityTest.models import Questionnaire
from riasec.models import RIASEC_Test
from administration.models import AdminScheduledConsultation


class SearchForm(forms.Form):
    name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Search username',
    }))


class AddRQuestionsForm(forms.ModelForm):
    class Meta:
        model = RIASEC_Test
        fields = ('question', 'category')

        category_choices = [
            ('R', 'Realistic'),
            ('I', 'Investigative'),
            ('A', 'Artistic'),
            ('S', 'Social'),
            ('E', 'Enterprising'),
            ('C', 'Conventional'),
        ]
        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}, choices=category_choices),
        }


class AddPQuestionsForm(forms.ModelForm):
    class Meta:
        model = Questionnaire
        fields = ('question', 'category', 'key')

        category_choices = [
            ('EXT', 'Extroversion'),
            ('EST', 'Neurotic'),
            ('AGR', 'Agreeable'),
            ('CSN', 'Conscientious'),
            ('OPN', 'Openness'),
        ]

        key_choices = [
            ('1', 'Positive'),
            ('0', 'Negative')
        ]

        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}, choices=category_choices),
            'key': forms.Select(attrs={'class': 'form-select'}, choices=key_choices),
        }


class ScheduleDateForm(forms.ModelForm):

    scheduled_date = forms.DateTimeField(required=True, widget=forms.DateTimeInput(attrs={
        'type': 'datetime-local',
        'class': 'form-control'
    }))

    managed_by = forms.ModelChoiceField(required=True, queryset=Profile.objects.filter(user__is_superuser=True), widget=forms.Select(attrs={
        'class': 'form-select'
    }))
    user = forms.ModelChoiceField(required=True, queryset=Profile.objects.all(), widget=forms.HiddenInput(attrs={
        'class': 'form-select'
    }))
    is_done = forms.BooleanField(required=False, widget=forms.HiddenInput())


    class Meta:
        model = AdminScheduledConsultation
        fields = ['scheduled_date', 'managed_by', 'user', 'is_done']

psytests/administration/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import ObjectDoesNotExist
from django.http import request
from django.http.response import Http404, HttpResponseBadRequest, HttpResponseRedirect
from django.urls.base import reverse
from django.views.generic import (
    TemplateView,
    ListView,
    UpdateView,
    DetailView,
    CreateView,
    DeleteView,
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
    PermissionRequiredMixin,
)
from django.views.generic import View
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic.edit import FormMixin

from personalityTest.models import Questionnaire, Result
from psytests.forms import ContactForm
from riasec.models import RIASEC_Test, Riasec_result

from datetime import datetime

from .forms import ScheduleDateForm, SearchForm, AddRQuestionsForm, AddPQuestionsForm
from .models import AdminScheduledConsultation

from accounts.models import Profile
from accounts.forms import UpdateUserForm

from django.core.mail import send_mail
from django.conf import settings

now = datetime.today()

# Create your views here.
class SuperUserCheck(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["unapproved_users"] = (
            Profile.objects.filter(is_assigned=False)
            .exclude(user__username=self.request.user)
            .count()
        )
        notif_count = (
            AdminScheduledConsultation.objects.filter(
                managed_by__user=self.request.user,
                is_done=False,
                scheduled_date__date=now.date(),
                scheduled_date__time__gt=now.time(),
                user__is_assigned=True,
            ).count()
            + AdminScheduledConsultation.objects.filter(
                managed_by__user=self.request.user,
                is_done=False,
                scheduled_date__lt=now.today(),
                user__is_assigned=True,
            ).count()
        )
        context["notif_count"] = notif_count if notif_count is not None else None

        return context


class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect_to_login(
                self.request.get_full_path(),
                self.get_login_url(),
                self.get_redirect_field_name(),
            )
        if not self.has_permission():
            return redirect("")
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)


class Home(LoginRequiredMixin, SuperUserCheck, TemplateView):
    template_name = "administration/admin_home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class UserManagement(LoginRequiredMixin, SuperUserCheck, ListView):
    template_name = "administration/user_management.html"
    model = User
    context_object_name = "users"
    paginate_by = 8

    def get_queryset(self):
        query = self.request.GET.get("name")
        if query:
            object_list = self.model.objects.filter(username__icontains=query).exclude(
                username=self.request.user
            )
        else:
            object_list = self.model.objects.exclude(username=self.request.user)
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm
        context["users_total"] = self.get_queryset().count()

        return context


class UserDetailUpdate(LoginRequiredMixin, SuperUserCheck, UpdateView):
    template_name = "administration/user_detail_update.html"
    model = User
    form_class = UpdateUserForm
    success_url = reverse_lazy("administration:user-management")


class PendingUsers(LoginRequiredMixin, SuperUserCheck, ListView):
    template_name = "administration/pending-users.html"
    model = Profile
    context_object_name = "users"
    paginate_by = 4

    def get_queryset(self):
        query = self.request.GET.get("name")
        if query:
            object_list = (
                self.model.objects.filter(
                    user__username__icontains=query, is_assigned=False
                )
                .order_by("is_assigned")
                .exclude(user__username=self.request.user)
            )
        else:
            obj_excluded = self.model.objects.exclude(user__username=self.request.user)
            object_list = obj_excluded.filter(is_assigned=False)
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm
        context["users_pending"] = (
            Profile.objects.filter(is_assigned=False)
            .exclude(user__username=self.request.user)
            .count()
        )
        context["users_assigned"] = (
            AdminScheduledConsultation.objects.filter(user__is_assigned=True)
            .exclude(managed_by=Profile.objects.get(user__username=self.request.user))
            .count()
        )
        return context


class AssignedUsers(LoginRequiredMixin, SuperUserCheck, ListView):
    template_name = "administration/assigned-users.html"
    model = AdminScheduledConsultation
    context_object_name = "users"
    paginate_by = 4

    def get_queryset(self):
        query = self.request.GET.get("name")
        if query:
            object_list = self.model.objects.filter(
                user__user__username__icontains=query, user__is_assigned=True
            ).exclude(user__user__username=self.request.user)
        else:
            obj = Profile.objects.get(user__username=self.request.user)
            obj_excluded = self.model.objects.exclude(managed_by=obj)
            object_list = obj_excluded.filter(user__is_assigned=True)
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm
        context["users_assigned"] = (
            AdminScheduledConsultation.objects.filter(user__is_assigned=True)
            .exclude(managed_by=Profile.objects.get(user__username=self.request.user))
            .count()
        )
        context["users_pending"] = (
            Profile.objects.filter(is_assigned=False)
            .exclude(user__username=self.request.user)
            .count()
        )
        return context

class UserDetailViewMixin(UserPassesTestMixin):
    
    def test_func(self):
        obj = get_object_or_404(Profile, user__username = self.request.user)
        
        if obj.user.is_superuser:
            test = True
            if obj.user.username == self.kwargs['user']:
                if obj.is_result == False:
                    test = False
        elif obj.is_result:
            if obj.user.username == self.kwargs['user']: 
                test = True
            else: 
                test = False
        else:
            test = False
        return test
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["unapproved_users"] = (
            Profile.objects.filter(is_assigned=False)
            .exclude(user__username=self.request.user)
            .count()
        )
        notif_count = (
            AdminScheduledConsultation.objects.filter(
                managed_by__user=self.request.user,
                is_done=False,
                scheduled_date__date=now.date(),
                scheduled_date__time__gt=now.time(),
                user__is_assigned=True,
            ).count()
            + AdminScheduledConsultation.objects.filter(
                managed_by__user=self.request.user,
                is_done=False,
                scheduled_date__lt=now.today(),
                user__is_assigned=True,
            ).count()
        )
        context["notif_count"] = notif_count if notif_count is not None else None

        return context

class UserDetailView(LoginRequiredMixin, UserDetailViewMixin, FormMixin, DetailView):
    template_name = "stats/stats.html"
    model = User
    form_class = ContactForm
    context_object_name = "user"

    def get_success_url(self):
        return reverse_lazy(
            "administration:user_detail",
            kwargs={"user": self.kwargs["user"], "pk": self.kwargs["pk"]},
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            obj = Profile.objects.get(user__username=self.kwargs.get("user"))
            context["profile"] = obj
        except:
            pass

        try:
            obj = AdminScheduledConsultation.objects.get(
                user__user__username=self.kwargs.get("user")
            )
            context["admin"] = obj
            if obj.is_done == True:
                context["done"] = obj.is_done
            if obj.scheduled_date:
                context["scheduled"] = obj.scheduled_date
        except:
            pass

        try:
            context["riasec_result"] = Riasec_result.objects.get(
                user__username=self.kwargs.get("user"), user__id=self.kwargs.get("pk")
            )
            obj = (
                Riasec_result.objects.filter(
                    user__username=self.kwargs.get("user"),
                    user__id=self.kwargs.get("pk"),
                )
                .values(
                    "realistic",
                    "investigative",
                    "artistic",
                    "social",
                    "enterprising",
                    "conventional",

psytests/administration/templates/administration/schedules/history.html
{% extends 'administration/base.html' %}
{% load static %}
{% block title %}History{% endblock %}

{% block content %}
    <header>
        {% include 'partials/_navbar.html' %}
    </header>
    <main class="container">
        <div class="row justify-content-center mt-3">
            <div class="col-sm-4 col-xs-6">
                <h1>Schedule Log</h1>
                <div class="list-group">
                    <a href="{% url 'administration:schedules' %}" class="list-group-item item-badge-between link-teal">
                        Today's Appointment
                        <span class="badge bg-info">{{user_count}}</span>
                    </a>
                    <a href="{% url 'administration:missed-schedules' %}" class="list-group-item item-badge-between link-teal">
                        Missed
                        <span class="badge bg-danger">{{late_count}}</span>
                    </a>
                    <a href="{% url 'administration:upcoming-schedules' %}" class="list-group-item item-badge-between link-teal">
                        Upcoming
                        <span class="badge bg-warning">{{upcoming_count}}</span>
                    </a>
                    <a href="{% url 'administration:history-schedules' %}" class="list-group-item link-teal">History</a>
                  </div>
            </div>
            <div class="col-sm-8 col-xs-6 pt-5">
                <h3>History</h3>
                {% if history %}
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Approved Time</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for user in history %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{user.user.user.first_name}}</td>
                            <td>{{user.user.user.last_name}}</td>
                            <td></td>
                            <td>
                              <div class="d-flex justify-content-evenly">
                              <a href="{% url 'administration:user_detail' user.user.user.username user.user.user.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="#5F4B8BFF"
                                  class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
                                  <path fill-rule="evenodd"
                                    d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z" />
                                  <path fill-rule="evenodd"
                                    d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z" />
                                </svg>
                              </a>
                              <a href="{% url 'administration:reset-schedule' user.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#E69A8DFF"
                                  class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
                                  <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z" />
                                  <path
                                    d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z" />
                                </svg>
                              </a>
                              <a href="#" type="button" data-bs-toggle="modal" data-bs-target="#return_{{user.user.user.username}}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="#4d4d4d" class="bi bi-arrow-90deg-right" viewBox="0 0 16 16">
                                  <path fill-rule="evenodd" d="M14.854 4.854a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 4H3.5A2.5 2.5 0 0 0 1 6.5v8a.5.5 0 0 0 1 0v-8A1.5 1.5 0 0 1 3.5 5h9.793l-3.147 3.146a.5.5 0 0 0 .708.708l4-4z"/>
                                </svg>
                              </a>
                              {% include 'administration/components/return_modal.html' %}
                            </div>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                </div>
                {% else %}
                  <div class="text-center">
                    <img class="w-75" src="{% static 'images/no-sched.png' %}" alt="">
                    <div>
                      <h3>
                        no history
                      </h3>
                    </div>
                  </div>
                  {% endif %}
                {% if is_paginated %}
      <nav aria-label="Page navigation" class="m-5">
        <ul class="pagination justify-content-end">
          {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
          {% endif %}
          {% for i in page_obj.paginator.page_range %}
          <li class="page-item {% if page_obj.number == i %}disabled{% endif %}"><a class="page-link"
              href="?page={{ i }}">{{i}}</a></li>
          {% endfor %}
          {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT
              &raquo;</a></li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
                
                
            </div>
        </div>
    </main>
{% endblock %}

psytests/administration/templates/administration/schedules/missed.html
{% extends 'administration/base.html' %}
{% load static %}

{% block title %}My Schedules | Missed{% endblock %}

{% block content %}
    <header>
        {% include 'partials/_navbar.html' %}
    </header>
    <main class="container">
        <div class="row justify-content-center mt-3">
            <div class="col-sm-4">
                <h1>Schedule Log</h1>
                <div class="list-group">
                    <a href="{% url 'administration:schedules' %}" class="list-group-item item-badge-between link-teal">
                        Today's Appointment
                        <span class="badge bg-info">{{user_count}}</span>
                    </a>
                    <a href="{% url 'administration:missed-schedules' %}" class="list-group-item item-badge-between link-teal">
                        Missed
                        <span class="badge bg-danger">{{late_count}}</span>
                    </a>
                    <a href="{% url 'administration:upcoming-schedules' %}" class="list-group-item item-badge-between link-teal">
                        Upcoming
                        <span class="badge bg-warning">{{upcoming_count}}</span>
                    </a>
                    <a href="{% url 'administration:history-schedules' %}" class="list-group-item link-teal">History</a>
                  </div>
            </div>
            <div class="col-xs-6 col-sm-8 pt-5">
                <h3>Missed Appointments</h3>
                {% if late %}
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Scheduled Date</th>
                            <th scope="col">Scheduled Time</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for user in late %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{user.user.user.first_name}}</td>
                            <td>{{user.user.user.last_name}}</td>
                            <td>{{user.scheduled_date.date}}</td>
                            <td>{{user.scheduled_date.time}}</td>
                            <td>
                              <div class="d-flex justify-content-evenly">
                              <a href="{% url 'administration:user_detail' user.user.user.username user.user.user.pk %}">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="#5F4B8BFF" class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
                                      <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
                                      <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
                                    </svg>
                              </a>
                                <a href="{% url 'administration:reset-schedule' user.pk %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#E69A8DFF" class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
                                        <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
                                      </svg>
                                </a>
                                <a href="#" type="button" data-bs-toggle="modal" data-bs-target="#approve_{{user.user.user.username}}">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="green" class="bi bi-check-lg" viewBox="0 0 16 16">
                                    <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
                                  </svg>
                                </a>
                                {% include 'administration/components/approve_modal.html' %}
                                <a href="#" type="button" data-bs-toggle="modal" data-bs-target="#return_{{user.user.user.username}}">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="#4d4d4d" class="bi bi-arrow-90deg-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M14.854 4.854a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 4H3.5A2.5 2.5 0 0 0 1 6.5v8a.5.5 0 0 0 1 0v-8A1.5 1.5 0 0 1 3.5 5h9.793l-3.147 3.146a.5.5 0 0 0 .708.708l4-4z"/>
                                  </svg>
                                </a>
                                {% include 'administration/components/return_modal.html' %}
                              </div>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                </div>
                {% else %}
                <div class="text-center">
                  <img class="w-75" src="{% static 'images/no-sched.png' %}" alt="">
                  <div>
                    <h3>
                      no missed appointments
                    </h3>
                  </div>
                </div>
                {% endif %}
                {% if is_paginated %}
      <nav aria-label="Page navigation" class="m-5">
        <ul class="pagination justify-content-end">
          {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
          {% endif %}
          {% for i in page_obj.paginator.page_range %}
          <li class="page-item {% if page_obj.number == i %}disabled{% endif %}"><a class="page-link"
              href="?page={{ i }}">{{i}}</a></li>
          {% endfor %}
          {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT
              &raquo;</a></li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
                
                
            </div>
        </div>
    </main>
{% endblock %}