psytests/administration/urls.py
from django.urls import path

from .views import (
    AssignedUsers,
    Home,
    PendingUsers,
    SetSchedule,
    UserDetailView,
    RQuestionsTemplateView,
    PQuestionsTemplateView,
    RQuestionsCreateView,
    PQuestionsCreateView,
    RQuestionsEditView,
    PQuestionsEditView,
    RDeleteQuestions,
    PDeleteQuestions,
    HistorySchedules,
    MissedSchedules,
    ResetSchedule,
    UpcomingSchedules,
    UserDetailUpdate,
    UserManagement,
    UserSchedules,
    approve_user,
    deleteRecord,
    return_user,
    send_msg,
)


app_name='administration'

urlpatterns=[
    path('', Home.as_view(), name='home'),
    path('user-management/', UserManagement.as_view(), name='user-management'),
    path('user-management/<int:pk>/update', UserDetailUpdate.as_view(), name='user-detail-update'),
    path('pending-users/', PendingUsers.as_view(), name='pending-users'),
    path('assigned-users/', AssignedUsers.as_view(), name='assigned-users'),
    path('user-results/<user>/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user-results/<user>/<int:pk>/approve', approve_user, name='approve-user'),
    path('user-results/<user>/<int:pk>/return', return_user, name='return-user'),
    path('user-results/delete/<int:r_pk>/<r_user>/<int:p_pk>/<p_user>/', deleteRecord, name='delete-record'),
    path('user-results/<username>/set-schedule/', SetSchedule.as_view(), name='set-schedule'),
    path('schedules/', UserSchedules.as_view(), name='schedules'),
    path('schedules/missed/', MissedSchedules.as_view(), name='missed-schedules'),
    path('schedules/upcoming/', UpcomingSchedules.as_view(), name='upcoming-schedules'),
    path('schedules/history/', HistorySchedules.as_view(), name='history-schedules'),
    path('schedules/<int:pk>/reset-schedule/', ResetSchedule.as_view(), name='reset-schedule'),
    path('rquestions/', RQuestionsTemplateView.as_view(), name='rquestions'),
    path('pquestions/', PQuestionsTemplateView.as_view(), name='pquestions'),
    path('rquestions/create/riasec/', RQuestionsCreateView.as_view(), name='rquestions_add'),
    path('pquestions/create/personality/', PQuestionsCreateView.as_view(), name='pquestions_add'),
    path('rquestions/<slug:slug>/riasec/edit', RQuestionsEditView.as_view(), name='rquestions_edit'),
    path('pquestions/<slug:slug>/personality/edit', PQuestionsEditView.as_view(), name='pquestions_edit'),
    path('rquestions/<slug:slug>/riasec/delete', RDeleteQuestions.as_view(), name='rquestions_delete'),
    path('pquestions/<slug:slug>/personality/delete', PDeleteQuestions.as_view(), name='pquestions_delete'),
    path('<user>/send-msg', send_msg, name='send-msg'),
]

psytests/psytests/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from accounts.forms import CustomizedPasswordResetForm, CustomizedPasswordResetConfirmForm
from psytests.views import Assessment, DataPrivacyConsent, HomePageView, Awesome

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
        path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset_form.html', email_template_name='accounts/password_reset_email.html', form_class=CustomizedPasswordResetForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', form_class=CustomizedPasswordResetConfirmForm), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('', HomePageView.as_view(), name="homepage"),
    path('assessment/', Assessment.as_view(), name="assessment"),
    path('awesome/', Awesome.as_view(), name="awesome"),
    path('<str:test>/data/privacy/consent', DataPrivacyConsent.as_view(), name="consent"),
    path('auth/', include('accounts.urls')), #Connects to psytest folder urls.py
    path('career/',include('riasec.urls')), #Connects to riasec folder urls.py
    path('personality/',include('personalityTest.urls')), #Connects to personalityTest folder urls.py
    path('accounts/', include('allauth.urls')),
    path('administration/', include('administration.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psytests/riasec/urls.py
from django.urls import path
from .views import Home, ResultPage
from . import views

app_name='riasec'
urlpatterns = [
    path('test/', views.testPage, name='test'),
    path('home/', Home.as_view(), name='home'),
    path('result/', ResultPage.as_view(), name='result'),
    path('test/evaluate/', views.evaluate, name='test_evaluate'),
]

psytests/administration/models.py
from django.db import models
from accounts.models import Profile

# Create your models here.

class AdminScheduledConsultation(models.Model):
    managed_by = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True, related_name='admin_name')
    user = models.OneToOneField(Profile, on_delete=models.CASCADE, null=True, blank=True, related_name='clients')
    # approved_time = models.DateTimeField(null=True, blank=True)
    scheduled_date = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)

    def __str__(self):
        return f'manage by {self.managed_by.user.username} to {self.user.user.username}'

psytests/personalityTest/models.py
from django.db import models
from django.db.models.fields import CharField
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Questionnaire(models.Model):

    class Meta:
        verbose_name = _('Questionnaire')
        verbose_name_plural = _('Questionnaires')
        # ordering = ('-id',)

    category_choices =[
        ('EXT','Extroversion'),
        ('EST','Neurotic'),
        ('AGR','Agreeable'),
        ('CSN','Conscientious'),
        ('OPN','Openness'),
    ]

    key_choices = [
        ('1', 'Positive'),
        ('0', 'Negative')
    ]

    question=models.TextField(editable=True)
    slug=models.SlugField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=100, choices=category_choices)
    key = models.CharField(max_length=10, null=True, blank=True, choices=key_choices)

    def __str__(self):
        return f"{str(self.question)}"

    def save(self,*args, **kwargs):
        self.slug = slugify(self.question)
        return super(Questionnaire, self).save(*args, **kwargs)


class Cluster(models.Model):
    cluster = models.CharField(max_length=10)
    extroversion = models.FloatField(default=0)
    neurotic = models.FloatField(default=0)
    agreeable = models.FloatField(default=0)
    conscientious = models.FloatField(default=0)
    openness = models.FloatField (default=0)

    def __str__(self):
        return self.cluster

class Result(models.Model):
    user=models.OneToOneField(User,null=True, on_delete=models.CASCADE)
    extroversion = models.FloatField(default=0)
    neurotic = models.FloatField(default=0)
    agreeable = models.FloatField(default=0)
    conscientious = models.FloatField(default=0)
    openness = models.FloatField (default=0)
    prediction = models.ForeignKey(Cluster, on_delete=models.CASCADE, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{str(self.user)}"

psytests/riasec/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _ #used for changing name in admin

class RIASEC_Test(models.Model):
    class Meta:
        verbose_name = _('RIASEC Test')
        verbose_name_plural = _('RIASEC Tests')

    category_choices =[
        ('R','Realistic'),
        ('I','Investigative'),
        ('A','Artistic'),
        ('S','Social'),
        ('E','Enterprising'),
        ('C', 'Conventional'),
    ]
    question=models.TextField()
    slug = models.SlugField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=100, choices=category_choices)

    def __str__(self):
        return str(self.question)

    def save(self,*args, **kwargs):
            self.slug=slugify(self.question)
            return super(RIASEC_Test, self).save(*args, **kwargs)

class Riasec_result (models.Model):
    class Meta:
        verbose_name = _('RIASEC Result')
        verbose_name_plural = _('RIASEC Results')

    user=models.OneToOneField(User,null=True, on_delete=models.CASCADE)
    realistic = models.FloatField(default=0)
    investigative = models.FloatField(default=0)
    artistic = models.FloatField(default=0)
    social = models.FloatField(default=0)
    enterprising = models.FloatField (default=0)
    conventional = models.FloatField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    

psytests/administration/forms.py
from django import forms
from accounts.models import Profile

from personalityTest.models import Questionnaire
from riasec.models import RIASEC_Test

from personalityTest.models import Questionnaire
from riasec.models import RIASEC_Test
from administration.models import AdminScheduledConsultation


class SearchForm(forms.Form):
    name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Search username',
    }))


class AddRQuestionsForm(forms.ModelForm):
    class Meta:
        model = RIASEC_Test
        fields = ('question', 'category')

        category_choices = [
            ('R', 'Realistic'),
            ('I', 'Investigative'),
            ('A', 'Artistic'),
            ('S', 'Social'),
            ('E', 'Enterprising'),
            ('C', 'Conventional'),
        ]
        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}, choices=category_choices),
        }


class AddPQuestionsForm(forms.ModelForm):
    class Meta:
        model = Questionnaire
        fields = ('question', 'category', 'key')

        category_choices = [
            ('EXT', 'Extroversion'),
            ('EST', 'Neurotic'),
            ('AGR', 'Agreeable'),
            ('CSN', 'Conscientious'),
            ('OPN', 'Openness'),
        ]

        key_choices = [
            ('1', 'Positive'),
            ('0', 'Negative')
        ]

        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}, choices=category_choices),
            'key': forms.Select(attrs={'class': 'form-select'}, choices=key_choices),
        }


class ScheduleDateForm(forms.ModelForm):

    scheduled_date = forms.DateTimeField(required=True, widget=forms.DateTimeInput(attrs={
        'type': 'datetime-local',
        'class': 'form-control'
    }))

    managed_by = forms.ModelChoiceField(required=True, queryset=Profile.objects.filter(user__is_superuser=True), widget=forms.Select(attrs={
        'class': 'form-select'
    }))
    user = forms.ModelChoiceField(required=True, queryset=Profile.objects.all(), widget=forms.HiddenInput(attrs={
        'class': 'form-select'
    }))
    is_done = forms.BooleanField(required=False, widget=forms.HiddenInput())


    class Meta:
        model = AdminScheduledConsultation
        fields = ['scheduled_date', 'managed_by', 'user', 'is_done']

psytests/administration/templates/administration/questions/pquestions.html
{% extends 'administration/base.html' %}
{% load static %}

{% block title %}Personality Questions{% endblock %}

{% block content %}
<header>
    {% include 'partials/_navbar.html' %}
</header>
<main class="container-fluid">
    {% if pquestions %}
    <div class="d-flex justify-content-center  ">
        <div class="col-sm-8 colxs-6 mt-3">
            <div class="d-flex justify-content-between">
                <div>
                    <h3>Personality Test Questionnaires</h3>
                </div>
                <div class="d-flex align-self-center">
                    <a href="{% url 'administration:pquestions_add' %}" class="link-teal">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                            class="bi bi-plus-square-fill me-3 " viewBox="0 0 16 16">
                            <path
                                d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z" />
                        </svg>
                    </a>
                </div>
            </div>
            <hr>
            
            {% for question in pquestions %}
            <div class="d-flex justify-content-between mb-2">
                <div>
                    <span>{{ forloop.counter0|add:page_obj.start_index }}.)</span>
                    <span>{{question.get_category_display}} - {{question|capfirst}}</span>
                </div>
                <div class="d-flex align-items-center ms-3">
                    <span class="me-2">{{question.get_key_display}}</span>
                    <a class="text-secondary" style="text-decoration:none;"
                        href="{% url 'administration:pquestions_edit' slug=question.slug %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                            class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                    </a>
                    <a href="#" class="" type="button" data-bs-toggle="modal"
                        data-bs-target="#pquestions_delete{{question.id}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="red" class="bi bi-trash"
                            viewBox="0 0 16 16">
                            <path
                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd"
                                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                </div>
            </div>
            {% include 'administration/components/pquestion_delete_modal.html' %}
            {% endfor %}
            {% endif %}
            {% if is_paginated %}
            <nav aria-label="Page navigation" class="mt-5">
                <ul class="pagination justify-content-end m-0">
                    {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == i %}disabled{% endif %}"><a class="page-link"
                            href="?page={{ i }}">{{i}}</a></li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT
                            &raquo;</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

psytests/administration/templates/administration/questions/pquestions_add.html
{% extends 'personalityTest/base.html' %}
{% load static %}

{% block title %}Add/Edit Personality Test Questionnaires{% endblock %}

{% block content %}
<main class="container w-50">
    <div class="mt-5">
        <div class="text-center">
            <h3>Personality Test Questionnaire Edit/Add</h3>
        </div>
    </div>
    <div class="border-1-round-box p-3">
        <form method="post">
            {% csrf_token %}
            <div>
                <label for="">Question:</label>
                {{form.question}}
            </div>
            <div class="mt-2">
                <label for="">Category:</label>
                {{form.category}}
            </div>
            <div class="mt-2">
                <label for="">Key:</label>
                {{form.key}}
            </div>
            <div class="text-center mt-2">
                <input class="btn btn-teal" type="submit">
            </div>
        </form>
    </div>
    </main>

</div>
{% endblock %}

psytests/administration/templates/administration/questions/rquestions.html
{% extends 'administration/base.html' %}
{% load static %}

{% block title %}Career Questions{% endblock %}

{% block content %}
<header>
    {% include 'partials/_navbar.html' %}
</header>
<main class="container-fluid">

    {% if rquestions %}
    <div class="row justify-content-center">
        <div class="col-sm-8 col-xs-6 mt-3">
            <div class="d-flex justify-content-between">
                <div>
                    <h3>Career Test Questionnaires</h3>
                </div>
                <div class="d-flex align-self-center">
                    <a href="{% url 'administration:rquestions_add' %}" class="link-teal">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                            class="bi bi-plus-square-fill me-3 " viewBox="0 0 16 16">
                            <path
                                d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z" />
                        </svg>
                    </a>
                </div>
            </div>
            <hr>

            {% for question in rquestions %}
            <div class="d-flex justify-content-between mb-2">
                <div>
                    <span>{{ forloop.counter0|add:page_obj.start_index }}.)</span>
                    <span>{{question.get_category_display}} - {{question|capfirst}}</span>
                </div>
                <div class="d-flex align-items-center ms-5">
                    <a style="text-decoration:none;"
                        href="{% url 'administration:rquestions_edit' slug=question.slug %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="gray"
                            class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                    </a>
                    <a href="#" data-bs-toggle="modal" data-bs-target="#rquestions_delete{{question.id}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="red" class="bi bi-trash"
                            viewBox="0 0 16 16">
                            <path
                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd"
                                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                </div>
            </div>
            {% include 'administration/components/rquestion_delete_modal.html' %}
            {% endfor %}
            {% endif %}

            <!-- Page -->
            {% if is_paginated %}
            <nav aria-label="Page navigation" class="mt-5">
                <ul class="pagination justify-content-end m-0">
                    {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == i %}disabled{% endif %}"><a class="page-link"
                            href="?page={{ i }}">{{i}}</a></li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT
                            &raquo;</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

psytests/administration/templates/administration/questions/rquestions_add.html
{% extends 'personalityTest/base.html' %}

{% block title %}Add/Edit Career Test Questionnaires{% endblock %}

{% block content %}
<main class="container" style="max-width:800px">
    <div class="mt-5">
        <div class="text-center">
            <h3>Career Test Questionnaire Edit/Add</h3>
        </div>
    </div>
    <div class="border-1-round-box p-3">
        <form method="post">
            {% csrf_token %}
            <div>
                <label for="">Question:</label>
                {{form.question}}
            </div>
            <div class="mt-2">
                <label for="">Category</label>
                {{form.category}}
            </div>
            <div class="text-center mt-2">
                <input type="submit" class="btn btn-teal">
            </div>
        </form>
    </div>

</main>
{% endblock %}