psytests/administration/urls.py
from django.urls import path

from .views import (
    AssignedUsers,
    Home,
    PendingUsers,
    SetSchedule,
    UserDetailView,
    RQuestionsTemplateView,
    PQuestionsTemplateView,
    RQuestionsCreateView,
    PQuestionsCreateView,
    RQuestionsEditView,
    PQuestionsEditView,
    RDeleteQuestions,
    PDeleteQuestions,
    HistorySchedules,
    MissedSchedules,
    ResetSchedule,
    UpcomingSchedules,
    UserDetailUpdate,
    UserManagement,
    UserSchedules,
    approve_user,
    deleteRecord,
    return_user,
    send_msg,
)


app_name='administration'

urlpatterns=[
    path('', Home.as_view(), name='home'),
    path('user-management/', UserManagement.as_view(), name='user-management'),
    path('user-management/<int:pk>/update', UserDetailUpdate.as_view(), name='user-detail-update'),
    path('pending-users/', PendingUsers.as_view(), name='pending-users'),
    path('assigned-users/', AssignedUsers.as_view(), name='assigned-users'),
    path('user-results/<user>/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user-results/<user>/<int:pk>/approve', approve_user, name='approve-user'),
    path('user-results/<user>/<int:pk>/return', return_user, name='return-user'),
    path('user-results/delete/<int:r_pk>/<r_user>/<int:p_pk>/<p_user>/', deleteRecord, name='delete-record'),
    path('user-results/<username>/set-schedule/', SetSchedule.as_view(), name='set-schedule'),
    path('schedules/', UserSchedules.as_view(), name='schedules'),
    path('schedules/missed/', MissedSchedules.as_view(), name='missed-schedules'),
    path('schedules/upcoming/', UpcomingSchedules.as_view(), name='upcoming-schedules'),
    path('schedules/history/', HistorySchedules.as_view(), name='history-schedules'),
    path('schedules/<int:pk>/reset-schedule/', ResetSchedule.as_view(), name='reset-schedule'),
    path('rquestions/', RQuestionsTemplateView.as_view(), name='rquestions'),
    path('pquestions/', PQuestionsTemplateView.as_view(), name='pquestions'),
    path('rquestions/create/riasec/', RQuestionsCreateView.as_view(), name='rquestions_add'),
    path('pquestions/create/personality/', PQuestionsCreateView.as_view(), name='pquestions_add'),
    path('rquestions/<slug:slug>/riasec/edit', RQuestionsEditView.as_view(), name='rquestions_edit'),
    path('pquestions/<slug:slug>/personality/edit', PQuestionsEditView.as_view(), name='pquestions_edit'),
    path('rquestions/<slug:slug>/riasec/delete', RDeleteQuestions.as_view(), name='rquestions_delete'),
    path('pquestions/<slug:slug>/personality/delete', PDeleteQuestions.as_view(), name='pquestions_delete'),
    path('<user>/send-msg', send_msg, name='send-msg'),
]

psytests/psytests/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from accounts.forms import CustomizedPasswordResetForm, CustomizedPasswordResetConfirmForm
from psytests.views import Assessment, DataPrivacyConsent, HomePageView, Awesome

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
        path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset_form.html', email_template_name='accounts/password_reset_email.html', form_class=CustomizedPasswordResetForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', form_class=CustomizedPasswordResetConfirmForm), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('', HomePageView.as_view(), name="homepage"),
    path('assessment/', Assessment.as_view(), name="assessment"),
    path('awesome/', Awesome.as_view(), name="awesome"),
    path('<str:test>/data/privacy/consent', DataPrivacyConsent.as_view(), name="consent"),
    path('auth/', include('accounts.urls')), #Connects to psytest folder urls.py
    path('career/',include('riasec.urls')), #Connects to riasec folder urls.py
    path('personality/',include('personalityTest.urls')), #Connects to personalityTest folder urls.py
    path('accounts/', include('allauth.urls')),
    path('administration/', include('administration.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psytests/riasec/urls.py
from django.urls import path
from .views import Home, ResultPage
from . import views

app_name='riasec'
urlpatterns = [
    path('test/', views.testPage, name='test'),
    path('home/', Home.as_view(), name='home'),
    path('result/', ResultPage.as_view(), name='result'),
    path('test/evaluate/', views.evaluate, name='test_evaluate'),
]

psytests/administration/models.py
from django.db import models
from accounts.models import Profile

# Create your models here.

class AdminScheduledConsultation(models.Model):
    managed_by = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True, related_name='admin_name')
    user = models.OneToOneField(Profile, on_delete=models.CASCADE, null=True, blank=True, related_name='clients')
    # approved_time = models.DateTimeField(null=True, blank=True)
    scheduled_date = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)

    def __str__(self):
        return f'manage by {self.managed_by.user.username} to {self.user.user.username}'

psytests/psytests/forms.py
from django import forms
from django import forms
from django.forms import widgets

class ContactForm(forms.Form):
    subject = forms.CharField(required=True ,max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    message = forms.CharField(required=True, max_length=360, widget=forms.Textarea(attrs={
        'class': 'form-control'
    }))

psytests/administration/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import ObjectDoesNotExist
from django.http import request
from django.http.response import Http404, HttpResponseBadRequest, HttpResponseRedirect
from django.urls.base import reverse
from django.views.generic import (
    TemplateView,
    ListView,
    UpdateView,
    DetailView,
    CreateView,
    DeleteView,
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
    PermissionRequiredMixin,
)
from django.views.generic import View
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic.edit import FormMixin

from personalityTest.models import Questionnaire, Result
from psytests.forms import ContactForm
from riasec.models import RIASEC_Test, Riasec_result

from datetime import datetime

from .forms import ScheduleDateForm, SearchForm, AddRQuestionsForm, AddPQuestionsForm
from .models import AdminScheduledConsultation

from accounts.models import Profile
from accounts.forms import UpdateUserForm

from django.core.mail import send_mail
from django.conf import settings

now = datetime.today()

# Create your views here.
class SuperUserCheck(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["unapproved_users"] = (
            Profile.objects.filter(is_assigned=False)
            .exclude(user__username=self.request.user)
            .count()
        )
        notif_count = (
            AdminScheduledConsultation.objects.filter(
                managed_by__user=self.request.user,
                is_done=False,
                scheduled_date__date=now.date(),
                scheduled_date__time__gt=now.time(),
                user__is_assigned=True,
            ).count()
            + AdminScheduledConsultation.objects.filter(
                managed_by__user=self.request.user,
                is_done=False,
                scheduled_date__lt=now.today(),
                user__is_assigned=True,
            ).count()
        )
        context["notif_count"] = notif_count if notif_count is not None else None

        return context


class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect_to_login(
                self.request.get_full_path(),
                self.get_login_url(),
                self.get_redirect_field_name(),
            )
        if not self.has_permission():
            return redirect("")
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)


class Home(LoginRequiredMixin, SuperUserCheck, TemplateView):
    template_name = "administration/admin_home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class UserManagement(LoginRequiredMixin, SuperUserCheck, ListView):
    template_name = "administration/user_management.html"
    model = User
    context_object_name = "users"
    paginate_by = 8

    def get_queryset(self):
        query = self.request.GET.get("name")
        if query:
            object_list = self.model.objects.filter(username__icontains=query).exclude(
                username=self.request.user
            )
        else:
            object_list = self.model.objects.exclude(username=self.request.user)
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm
        context["users_total"] = self.get_queryset().count()

        return context


class UserDetailUpdate(LoginRequiredMixin, SuperUserCheck, UpdateView):
    template_name = "administration/user_detail_update.html"
    model = User
    form_class = UpdateUserForm
    success_url = reverse_lazy("administration:user-management")


class PendingUsers(LoginRequiredMixin, SuperUserCheck, ListView):
    template_name = "administration/pending-users.html"
    model = Profile
    context_object_name = "users"
    paginate_by = 4

    def get_queryset(self):
        query = self.request.GET.get("name")
        if query:
            object_list = (
                self.model.objects.filter(
                    user__username__icontains=query, is_assigned=False
                )
                .order_by("is_assigned")
                .exclude(user__username=self.request.user)
            )
        else:
            obj_excluded = self.model.objects.exclude(user__username=self.request.user)
            object_list = obj_excluded.filter(is_assigned=False)
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm
        context["users_pending"] = (
            Profile.objects.filter(is_assigned=False)
            .exclude(user__username=self.request.user)
            .count()
        )
        context["users_assigned"] = (
            AdminScheduledConsultation.objects.filter(user__is_assigned=True)
            .exclude(managed_by=Profile.objects.get(user__username=self.request.user))
            .count()
        )
        return context


class AssignedUsers(LoginRequiredMixin, SuperUserCheck, ListView):
    template_name = "administration/assigned-users.html"
    model = AdminScheduledConsultation
    context_object_name = "users"
    paginate_by = 4

    def get_queryset(self):
        query = self.request.GET.get("name")
        if query:
            object_list = self.model.objects.filter(
                user__user__username__icontains=query, user__is_assigned=True
            ).exclude(user__user__username=self.request.user)
        else:
            obj = Profile.objects.get(user__username=self.request.user)
            obj_excluded = self.model.objects.exclude(managed_by=obj)
            object_list = obj_excluded.filter(user__is_assigned=True)
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm
        context["users_assigned"] = (
            AdminScheduledConsultation.objects.filter(user__is_assigned=True)
            .exclude(managed_by=Profile.objects.get(user__username=self.request.user))
            .count()
        )
        context["users_pending"] = (
            Profile.objects.filter(is_assigned=False)
            .exclude(user__username=self.request.user)
            .count()
        )
        return context

class UserDetailViewMixin(UserPassesTestMixin):
    
    def test_func(self):
        obj = get_object_or_404(Profile, user__username = self.request.user)
        
        if obj.user.is_superuser:
            test = True
            if obj.user.username == self.kwargs['user']:
                if obj.is_result == False:
                    test = False
        elif obj.is_result:
            if obj.user.username == self.kwargs['user']: 
                test = True
            else: 
                test = False
        else:
            test = False
        return test
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["unapproved_users"] = (
            Profile.objects.filter(is_assigned=False)
            .exclude(user__username=self.request.user)
            .count()
        )
        notif_count = (
            AdminScheduledConsultation.objects.filter(
                managed_by__user=self.request.user,
                is_done=False,
                scheduled_date__date=now.date(),
                scheduled_date__time__gt=now.time(),
                user__is_assigned=True,
            ).count()
            + AdminScheduledConsultation.objects.filter(
                managed_by__user=self.request.user,
                is_done=False,
                scheduled_date__lt=now.today(),
                user__is_assigned=True,
            ).count()
        )
        context["notif_count"] = notif_count if notif_count is not None else None

        return context

class UserDetailView(LoginRequiredMixin, UserDetailViewMixin, FormMixin, DetailView):
    template_name = "stats/stats.html"
    model = User
    form_class = ContactForm
    context_object_name = "user"

    def get_success_url(self):
        return reverse_lazy(
            "administration:user_detail",
            kwargs={"user": self.kwargs["user"], "pk": self.kwargs["pk"]},
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            obj = Profile.objects.get(user__username=self.kwargs.get("user"))
            context["profile"] = obj
        except:
            pass

        try:
            obj = AdminScheduledConsultation.objects.get(
                user__user__username=self.kwargs.get("user")
            )
            context["admin"] = obj
            if obj.is_done == True:
                context["done"] = obj.is_done
            if obj.scheduled_date:
                context["scheduled"] = obj.scheduled_date
        except:
            pass

        try:
            context["riasec_result"] = Riasec_result.objects.get(
                user__username=self.kwargs.get("user"), user__id=self.kwargs.get("pk")
            )
            obj = (
                Riasec_result.objects.filter(
                    user__username=self.kwargs.get("user"),
                    user__id=self.kwargs.get("pk"),
                )
                .values(
                    "realistic",
                    "investigative",
                    "artistic",
                    "social",
                    "enterprising",
                    "conventional",

psytests/administration/templates/administration/components/approve_modal.html
<div class="modal fade" id="approve_{{user.user.user.username}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <h5>Are you sure to do you want to approve this user?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url 'administration:approve-user' user.user.user.username user.user.user.pk %}" class="btn btn-success me-3">Approve</a>
            </div>
        </div>
    </div>
</div>

psytests/administration/templates/administration/components/p-approve_modal.html
<div class="modal fade" id="approve_{{user.user.username}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <h5>Are you sure do you want to approve this user?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url 'administration:approve-user' user.user.username user.user.pk %}" class="btn btn-success me-3">Approve</a>
            </div>
        </div>
    </div>
</div>

psytests/administration/templates/administration/components/pquestion_delete_modal.html
<div class="modal fade" id="pquestions_delete{{question.id}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Question</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                Are you sure to delete this question?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url 'administration:pquestions_delete' slug=question.slug %}" class="btn btn-danger me-3">Delete</a>
            </div>
        </div>
    </div>
</div>

psytests/administration/templates/administration/components/return_modal.html
<div class="modal fade" id="return_{{user.user.user.username}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Confirm</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <p class="fs-18">Are you sure do you want to return this user to pending status?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url 'administration:return-user' user.user.user.username user.user.user.pk %}" class="btn btn-success me-3">Return</a>
            </div>
        </div>
    </div>
</div>

psytests/administration/templates/administration/components/rquestion_delete_modal.html
<div class="modal fade" id="rquestions_delete{{question.id}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Question</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                Are you sure to delete this question?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url 'administration:rquestions_delete' slug=question.slug  %}" class="btn btn-danger me-3">Delete</a>
            </div>
        </div>
    </div>
</div>

psytests/administration/templates/administration/components/send-msg-modal.html
<div class="modal fade" id="send_msg_{{user.user.username}}" tabindex="-1" aria-labelledby="message-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="message-label">Send your message here</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <form method="post" action="{% url 'administration:send-msg' user.user.username %}">
                {% csrf_token %}
                <div class="modal-body">
                <label class="mb-2" for="subject">Subject:</label>
                <input type="text" name="subject" class="form-control" maxlength="100" required="" id="id_subject">
                <label class="mb-2" for="message">Message:</label>    
                <textarea name="message" cols="40" rows="10" class="form-control" maxlength="360" required="" id="id_message"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">close</button>
                    <button type="submit" class="btn btn-success me-3">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>