psytests/accounts/urls.py
from django.urls import path
from .views import (
    registerPage,
    loginPage,
    logoutUser,
    activate,
)

app_name='accounts'
urlpatterns = [
    path('register/', registerPage, name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('login/', loginPage, name='login'),
    path('logout/',logoutUser,name='logout'),
]

psytests/psytests/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from accounts.forms import CustomizedPasswordResetForm, CustomizedPasswordResetConfirmForm
from psytests.views import Assessment, DataPrivacyConsent, HomePageView, Awesome

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
        path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset_form.html', email_template_name='accounts/password_reset_email.html', form_class=CustomizedPasswordResetForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', form_class=CustomizedPasswordResetConfirmForm), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('', HomePageView.as_view(), name="homepage"),
    path('assessment/', Assessment.as_view(), name="assessment"),
    path('awesome/', Awesome.as_view(), name="awesome"),
    path('<str:test>/data/privacy/consent', DataPrivacyConsent.as_view(), name="consent"),
    path('auth/', include('accounts.urls')), #Connects to psytest folder urls.py
    path('career/',include('riasec.urls')), #Connects to riasec folder urls.py
    path('personality/',include('personalityTest.urls')), #Connects to personalityTest folder urls.py
    path('accounts/', include('allauth.urls')),
    path('administration/', include('administration.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psytests/riasec/urls.py
from django.urls import path
from .views import Home, ResultPage
from . import views

app_name='riasec'
urlpatterns = [
    path('test/', views.testPage, name='test'),
    path('home/', Home.as_view(), name='home'),
    path('result/', ResultPage.as_view(), name='result'),
    path('test/evaluate/', views.evaluate, name='test_evaluate'),
]

psytests/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model

from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    gender_choices = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=6, choices=gender_choices, null=True, blank=True)
    is_assigned = models.BooleanField(null=True)
    is_result = models.BooleanField(default=False)
    
    def __str__(self):
        return self.user.username




@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

psytests/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.forms.widgets import Select, SelectDateWidget

from django.contrib.auth.forms import PasswordResetForm, PasswordChangeForm

from django.utils import timezone

import re

now = timezone.now()

class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'Password'
        self.fields['password2'].label = 'Confirm Password'
        self.fields['email'].label = 'Email Address'
        self.fields['username'].label = 'Username'
        self.fields['first_name'].label = 'First Name'
        self.fields['last_name'].label = 'Last Name'
        self.fields['gender'].label = 'Gender'
        self.fields['date_of_birth'].label = 'Date of Birth'

    year_range = list(range(now.year-100, now.year+1))
    year_range.reverse()

    gender_choices = [
            ('', '---'),
            ('M', 'Male'),
            ('F', 'Female'),
        ]
    date_of_birth = forms.DateField(required = False, widget=SelectDateWidget(empty_label=("Year", "Month", "Day"), years=year_range, attrs={
        'class': 'form-select'
    }))
    gender = forms.CharField(widget=Select(choices=gender_choices, attrs={
        'class': 'form-select'
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your first name',
        'autofocus': ''
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your last name'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your username'
    }))    
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your email address'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your password'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Re-enter password'
    }))
    is_superuser = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={
        'placeholder': 'is_superuser'
    }))

    class Meta:
        model=User
        fields = ['first_name', 'last_name','gender','date_of_birth','username','email','password1','password2', 'is_superuser']

    def clean_first_name(self):
        if not self.cleaned_data.get('first_name').replace(" ", "").isalpha():
            raise ValidationError("it shouldn't contain numbers")
        
        return self.cleaned_data.get('first_name')

    def clean_last_name(self):
        if not self.cleaned_data.get('last_name').replace(" ", "").isalpha():
            raise ValidationError("it shouldn't contain numbers")
        
        return self.cleaned_data.get('last_name')

    def clean_date_of_birth(self):
        try:
            date = self.cleaned_data.get('date_of_birth')
        except:
            raise ValidationError('Enter a valid date')
            
        return self.cleaned_data.get('date_of_birth')

    def clean_username(self):
        pattern = '^[A-Za-z0-9]+(?:[ _-][A-Za-z0-9]+)*$'
        username = self.cleaned_data.get('username')
        result = re.match(pattern, username)
        if not result:
            raise ValidationError('Invalid Username')
        
        if len(username) < 6:
            raise ValidationError('Username must be minimum to 6 characters')

        return username

    def clean_password1(self):
        pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$"
        password1 = self.cleaned_data.get('password1')
        result = re.match(pattern, password1)
        if not result:
            raise ValidationError('Invalid Password')
        
        return password1

    def clean_password2(self):
        if self.cleaned_data.get('password2') != self.cleaned_data.get('password1'):
            raise ValidationError("Confirmation password doesn't match")

        return self.cleaned_data.get('password2')

    def clean_email(self):
        pattern = '([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+'
        email = self.cleaned_data.get('email')
        result = re.fullmatch(pattern, email)

        try:
            User.objects.get(email=email)
            raise ValidationError('Email address already exist')
        except ObjectDoesNotExist:
            pass

        if not result:
            raise ValidationError('Invalid email address')

        return self.cleaned_data.get('email')

class UpdateUserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'Email Address'
        self.fields['username'].label = 'Username'
        self.fields['first_name'].label = 'First Name'
        self.fields['last_name'].label = 'Last Name'

    first_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your first name',
    }))
    last_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your last name'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your username'
    }))    
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your email address'
    }))
    is_superuser = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        'placeholder': 'is_superuser',
        'class': 'form-check-input',
    }))


    class Meta:
        model=User
        fields = ['first_name', 'last_name','username','email','is_superuser']

class CustomizedPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type your email address'
    }))

class CustomizedPasswordResetConfirmForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Old password'
    }))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type here'
    }))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Type here'
    }))

    def clean_new_password1(self):
        pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$"
        new_password1 = self.cleaned_data.get('new_password1')
        result = re.match(pattern, new_password1)
        if not result:
            raise ValidationError('Invalid Password')
        
        return new_password1

    def clean_new_password2(self):
        if self.cleaned_data.get('new_password2') != self.cleaned_data.get('new_password1'):
            raise ValidationError("Confirmation password doesn't match")

        return self.cleaned_data.get('new_password2')

psytests/accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.http.response import HttpResponse
from django.shortcuts import render,redirect, reverse
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from .forms import CreateUserForm
from .decorators import unauthenticated_user
# Create your views here.

from datetime import datetime

UserModel = get_user_model()
now = datetime.today()

def loginPage(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            messages.error(request, 'Username or Password is incorrect')
    return render(request,'accounts/login.html',{
        'day': now.strftime('%A'),
        'date': now.strftime('%B %d')
    })

def registerPage(request):
    if request.method == 'POST':
        form=CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user.refresh_from_db()
            user.profile.date_of_birth = form.cleaned_data.get('date_of_birth')
            user.profile.gender = form.cleaned_data.get('gender')
            user.save()

            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('accounts/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'accounts/emailConfirmationView.html')
            
    else:
        form = CreateUserForm()
    context = {'form': form}
    return render(request,'accounts/register.html',context)


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'accounts/emailActivatedView.html')
    else:
        return render(request, 'accounts/emailActivationInvalidView.html')

def logoutUser(request):
    logout(request)
    return redirect('accounts:login')

psytests/accounts/templates/accounts/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}  
If you think, it's not you, then just ignore this email.  
{% endautoescape %}

psytests/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/login-register.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/accounts-css.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/fonts/font-awesome-4.7.0\css\font-awesome.min.css' %}">


    <title>{% block title %}Login{% endblock %}</title>
</head>

<body>
        {% block content %}
        {% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
    crossorigin="anonymous"></script>
</html>

psytests/accounts/templates/accounts/emailActivatedView.html
{% extends "accounts/base.html" %}
{% block title %}Account Activated{% endblock %}
{% block content %}


<div class="row justify-content-center px-5">
    <div class="col-sm-8 col-xs-6 border-1 mt-5 p-4">
        <div class="text-center">
            <h1>Email Activated</h1>
        </div>
        <div class="text-center">
            <p>Thank you for your email confirmation. Now you can <a href="{% url 'accounts:login' %}" class="link-teal">login</a>  your account.</p>
        </div>
    </div>
</div>
{% endblock %}

psytests/accounts/templates/accounts/emailActivationInvalidView.html
{% extends "accounts/base.html" %}
{% block title %}Email Activation Invalid{% endblock %}
{% block content %}


<div class="row justify-content-center px-5">
    <div class="col-sm-8 col-xs-6 border-1 mt-5 p-4">
        <div class="text-center">
            <h1>Activation Invalid</h1>
        </div>
        <div class="text-center">
            <p>Activation link is invalid!</p>
        </div>
    </div>
</div>
{% endblock %}

psytests/accounts/templates/accounts/emailConfirmationView.html
{% extends "accounts/base.html" %}
{% block title %}Email Confirmation{% endblock %}
{% block content %}


<div class="row justify-content-center px-5">
    <div class="col-sm-8 col-xs-6 border-1 mt-5 p-4">
        <div class="text-center">
            <h1>Email sent</h1>
        </div>
        <div class="text-center">
            <p>Please confirm your email address to complete the registration</p>
        </div>
    </div>
</div>
{% endblock %}

psytests/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}


{% load socialaccount %}
{% providers_media_js %}

{% load static %}


{% block title %}Login{% endblock %}


{% block content %}
<div class="container-fluid vh-100 login-bg">
    <div class="row justify-content-end">
        <div class="col-xs-6 col-sm-8">
            <div class="d-flex justify-content-end m-5">
                <div class="align-self-center mx-2">
                    <h1>PSYTEST</h1>
                </div>
                <div class="d-flex justify-content-center">
                    <img src="{% static 'images/jmcseal.png' %}" alt="" class="logo-50">
                    <img src="{% static 'images/cite.png' %}" alt="" class="logo-50">
                    <img src="{% static 'images/psychology.png' %}" alt="" class="logo-50">
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="mx-auto mt-5">
                <h3 class="text-center color-teal mb-3">Login to Continue</h3>
                <!-- form -->
                <form class="p-4 border rounded-3 bg-light" action="{% url 'accounts:login' %}" method="post">
                    {% csrf_token %}
                    <!-- input div -->
                    <div>
                        <div class="form-floating mb-3">
                            <input type="email/username" class="form-control" id="username"
                                placeholder="example@email.com" name='username' required>
                            <label for="username" class="text-muted">Username/Email</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="password" placeholder="example@email.com"
                                name='password' required>
                            <label for="password" class="text-muted">password</label>
                        </div>
                        <div class="d-flex justify-content-end custom-control custom-checkbox mb-4">
                            <!-- <div class="form-check form-check-inline">
                                <input class="form-check-input" type="checkbox" id="remember-me" value="rememberme">
                                <label class="form-check-label text-muted" for="remember-me">Remember me</label>
                            </div> -->
                            <a href="{% url 'password_reset' %}" class="fs-15">Forgot Password?</a>
                        </div>
                        <button class="btn-style btn w-100 fs-17 p-2 rounded-pill">Login</button>
                    </div>
                    <!-- or div -->
                    <div class="d-flex justify-content-center my-2">
                        <small class="separator w-50">or</small>
                    </div>
                    <!-- Social login div -->
                    <div class="d-flex flex-column">
                        <a href="{% provider_login_url 'google'%}"
                            class="login-google-social social-bg2 flex-c-m mt-2 btn w-100 p-4 rounded-pill"
                            type="button"><img src="{% static 'images/google.png' %}" alt="googleicon" id="google-icon">
                            <span>
                                Continue with Google
                            </span>
                        </a>
                        <a href="{% provider_login_url 'facebook' method='js_sdk' %}"
                            class="login-fb-social social-bg1 flex-c-m mt-2 btn w-100 p-4 rounded-pill" type="button">
                            <svg id="fb-icon" xmlns="http://www.w3.org/2000/svg" width="25" height="25"
                                fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                                <path
                                    d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                            </svg>
                            <span>
                                Continue with Facebook
                            </span>
                        </a>
                    </div>
                </form>
                <!-- error message div -->
                <div>
                    {% for message in messages %}
                    <p class="m-t-25 text-center" id="messages" style="color:red;">{{message}}</p>
                    {% endfor %}
                </div>
                <!-- sign up link div -->
                <div class="text-muted mt-3 text-center">Don't have an account? <a href="{% url 'accounts:register' %}"
                        style="color:#0d6efd">Sign up</a>
                    <div class="mt-2 text-center">
                        <small>By clicking Sign up, you agree to the terms of use.</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

psytests/accounts/templates/accounts/password_reset_complete.html
{% extends "accounts/base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}


<div class="row justify-content-center px-5">
    <div class="col-sm-8 col-xs-6 border-1 mt-5 p-4">
        <div class="text-center">
            <h1>Password set</h1>
        </div>
        <div>
            <p>Your password has been set. You can 
                <a href="{% url 'accounts:login' %}">log in now</a></p>
        </div>
    </div>
</div>
{% endblock %}

psytests/accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}

<div class="row justify-content-center px-5">
    <div class="col-sm-8 col-xs-6 border-1 mt-5 p-4">
        <div class="text-center">
            <h1>Reset your password</h1>
        </div>
        <div>
            {% if validlink %}
            <form method="post">
                {% csrf_token %}
                <fieldset>
                    <label for="id_old_password">Type your old password</label>
                    {{ form.old_password }}
                    {{form.old_password.errors}}
                    <p class="color-teal my-2">Please enter your new password twice:</p>
                    <label for="id_new_password1">Type your new password</label>
                    {{ form.new_password1 }}
                    {{form.new_password1.errors}}
                    {% if form.new_password1.errors %}
                    <div class="alert alert-secondary">
                        <p>Password should be:</p>
                        <ul>
                            <li>Minimum to eight characters</li>
                            <li>At least one uppercase letter</li>
                            <li>One lowercase letter and one
                                number</li>
                        </ul>
                    </div>
                    {% endif %}
                    <label for="id_new_password2">Confirm new password</label>
                    {{form.new_password2}}
                    {{form.new_password2.errors}}
                    <input  class="btn btn-teal mt-3" type="submit" value="Change my password" />
                </fieldset>
            </form>
            {% else %}
            <div>
                <p>The password reset link was invalid, possibly because it has
                    already been used. Please request a new password reset.</p>
                <div>
                    <a href="{% url 'password_reset' %}" class="link-teal">request again</a>
                </div>
            </div>
            
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

psytests/accounts/templates/accounts/password_reset_done.html
{% extends "accounts/base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}


<div class="row justify-content-center">
    <div class="col-6 border-1 m-t-75 p-4">
        <div class="text-center">
            <h1>Reset your password</h1>
        </div>
        <div>
            <p>We've emailed you instructions for setting your password.</p>
            <p>If you don't receive an email, please make sure you've entered 
           the address you registered with.</p>
        </div>
    </div>
</div>
{% endblock %}

psytests/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the 
link below:
{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

psytests/accounts/templates/accounts/password_reset_form.html
{% extends "accounts/base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<div class="row justify-content-center px-5">
    <div class="col-sm-8 col-xs-6 border-1 mt-5 p-4">
        <div class="text-center">
            <h1>Forgotten your password?</h1>
        </div>
        <div>
            <div class="my-3">
                <p>Enter your <strong>E-mail address</strong> to obtain a new password.</p>
            </div>
            <form method="post">
                <div class="input-group">
                    <input class='btn btn-teal' type="submit" value="Submit">
                    {{ form.email }}
                </div>

                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

psytests/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}


{% block title %}Register{% endblock %}

{% block content%}
<main class="container-fluid">
    <div class="row justify-content-center mt-3">
        <div class="col-sm-8 col-xs-6 p-4 border-1-round-box">
            <h3 class="mb-4">Register</h3>

            <form method="post">
                {% csrf_token %}
                <div class="row mb-3">
                    <div class="col-sm-6 col-xs-6">
                        <label for="">{{form.first_name.label}}</label>
                        {{form.first_name}}
                        <p class="text-danger ms-3">{{form.first_name.errors }}</p>
                    </div>
                    <div class="col-sm-6 col-xs-6">
                        <label for="">{{form.last_name.label}}</label>
                        {{form.last_name}}
                        <p class="text-danger ms-3">{{form.last_name.errors }}</p>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-6 col-xs-6">
                        <label for="">{{form.gender.label}}</label>
                        {{form.gender}}
                    </div>
                    <div class="col-sm-6 col-xs-6">
                        <label for="">{{form.date_of_birth.label}}</label>
                        <div class="input-group">{{form.date_of_birth}}</div>
                        {{form.date_of_birth.errors}}
                    </div>
                </div>
                <div class="mb-3">
                    <label for="">{{form.username.label}}</label>
                    {{form.username}}
                </div>
                {% if form.username.errors %}
                {{form.username.errors}}
                <div class="alert alert-secondary">
                    <ul>
                        <li>Usernames can consist of lowercase and capitals</li>
                        <li>Usernames can consist of alphanumeric characters</li>
                        <li>Usernames can consist of underscore and hyphens and spaces</li>
                        <li>Cannot be two underscores, two hypens or two spaces in a row</li>
                        <li>Cannot have a underscore, hypen or space at the start or end</li>
                    </ul>
                </div>
                {% endif %}
                <div class="mb-3">
                    <label for="">{{form.email.label}}</label>
                    {{form.email}}
                    {{form.email.errors}}
                </div>

                <div class="row mb-3">
                    <div class="col-sm-6 col-xs-6">
                        <label for="">{{form.password1.label}}</label>
                        {{form.password1}}
                        {{form.password1.errors}}
                    </div>
                    <div class="col-sm-6 col-xs-6">
                        <label for="">{{form.password2.label}}</label>
                        {{form.password2}}
                        {{form.password2.errors}}
                    </div>
                    {% if form.password1.errors %}
                    <div class="alert alert-secondary">
                        <p>Password should be:</p>
                        <ul>
                            <li>Minimum to eight characters</li>
                            <li>At least one uppercase letter</li>
                            <li>One lowercase letter and one
                                number</li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
                <div class="d-flex justify-content-center">
                    <input type="submit" value="Submit" class="btn btn-style w-100 mt-3">
                </div>
            </form>
        </div>
    </div>
</main>

{% endblock %}